name: Checar links do Markdown

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check-link:

    runs-on: ubuntu-22.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: '.github/mlc_config.json'
